### ISSUE TITLE
undefined method 'as'

### ISSUE THREAD

**Issue by youkyll** [seuros/capistrano-puma#229]
```
SSHKit::Runner::ExecuteError: Exception while executing as xxx@test.com: undefined method `as' for #<Capistrano::Puma:0x007fa7093ee150>

```

I got this error when executing puma commands after upgrading to v3.

https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/puma.rb#L11

**Comment by nicolasblanco** [comment]
@youkyll : I'm also hitting the same exception, has not found the problem yet, sorry 😭

**Comment by 4xposed** [comment]
I opened a PR that should fix this issue: https://github.com/seuros/capistrano-puma/pull/230

@youkyll  Feel free to try out my fork and see if that fixes it for you too.
