### ISSUE TITLE
puma:nginx_config and puma:config isn't working with capistrano 3.6.1

### ISSUE THREAD

**Issue by smoothdvd** [seuros/capistrano-puma#185]

**Comment by bombazook** [comment]
Maybe it wouldn't help you, but for nginx_config I needed passwordless sudo.
Also cap3 has very strange behaviour of configuration with different unix users for same domain.
Last one breaks many gems that need separate role for sudo.
I fixed it with no_release: true option for nginx role and different domain for it.
`server 'mydomain_1.com', user: 'deploy', roles: %w{web app db}
server 'mydomain_2.com', user: 'unix_sudoer_user', roles: %w{sudoer}, no_release: true`

**Comment by tom-lord** [comment]
I don't like the implementation to require passwordless sudo for updating the nginx config. Instead, I decided to just generate an nginx.conf file from the template:

```
namespace :nginx do 
  desc 'Re-generate the nginx configuration file, from template' 
  task :config do 
    on roles(fetch(:puma_nginx, :web)) do |role| 
      puma_switch_user(role) do 
        template_puma('nginx_conf', "#{release_path}/config/nginx.conf", role)
      end
    end
  end
end
```

...And on the production/staging servers, use a symbolic link to load the file:

    sudo ln -nfs /home/deploy/apps/<app-name>/current/config/nginx.conf /etc/nginx/sites-enabled/<app-name>

**Comment by patrickbrownsync** [comment]
None of my puma tasks work on Capistrano 3.6.1, they fail silently

**Comment by ccastillop** [comment]
Wrekic error with sshkit -v 1.11.5
But It works fine with sshkit ~> 1.10.0

```
** Invoke puma:nginx_config (first_time)
** Execute puma:nginx_config
cap aborted!
NoMethodError: undefined method `puma_switch_user' for #<SSHKit::Backend::Netssh:0x007febd8ce24c8>
/Users/ccastillop/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/capistrano3-puma-1.2.1/lib/capistrano/tasks/nginx.rake:5:in `block (3 levels) in <top (required)>'
/Users/ccastillop/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.5/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/ccastillop/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sshkit-1.11.5/lib/sshkit/backends/abstract.rb:29:in `run
```

**Comment by egoens** [comment]
I'm having the same issue that @patrickbrownsync is/was having. The odd thing is, I was able to get the server to start earlier this morning but for whatever reason it's no longer working:

**Earlier:**
```
➜  riding-forecast git:(master) ✗ cap production puma:start
00:00 puma:start
      using conf file /var/www/example.com/shared/puma.rb
      01 $HOME/.rbenv/bin/rbenv exec bundle exec puma -C /var/www/example.com/shared/puma.rb --daemon
      01 Puma starting in single mode...
      01
      01 * Version 3.8.2 (ruby 2.2.6-p396), codename: Sassy Salamander
      01
      01 * Min threads: 0, max threads: 16
      01
      01 * Environment: production
      01
      01 * Daemonizing...
      01
    ✔ 01 deploy@example.com 0.603s
```

**Now and consistenly:**
```
➜  riding-forecast git:(master) ✗ cap production puma:start  
➜  riding-forecast git:(master) ✗ 
```

What's odd about that, is that there were no configuration changes. I realize that doesn't help in terms of debugging the issue but not sure what/how to

**Comment by egoens** [comment]
:derp: I found the issue. I wasn't include the proper roles for the server user:

**Originally:**
`server "example.com", user: "deploy", roles: %w{web}`

**Fixed by:**
`server "example.com", user: "deploy", roles: %w{web app}`

**Comment by ivanovaleksey** [comment]
@tom-lord, nice solution but aren't we must reload nginx to allow it to fetch content of config file?
I don't see any reload in [nginx.rake](https://github.com/seuros/capistrano-puma/blob/master/lib/capistrano/tasks/nginx.rake). It is should be done manually after deploy?

**Comment by tom-lord** [comment]
@ivanovaleksey Yes, I also automated this with a Catistrano task that says "if the config has changed in this deploy (which it rarely does!), then restart nginx".

I don't have the exact code for my implementation of this at hand right now, but i could fetch it for you next week if you're stuck? I remember it being a little fiddly to get right (searching the "previous release path"), but otherwise pretty straight forward.

**Comment by ivanovaleksey** [comment]
@tom-lord that would be very kind of you.
Essentially I was curious about Monit and started using it.
I faced with the problem of running Monit as `sudo`.
TL;RD Currently I use [sshkit-sudo](https://github.com/kentaroi/sshkit-sudo) gem but you can see little history [here](https://github.com/seuros/capistrano-puma/pull/222#issuecomment-293244129).
Seems like there is some more appropriate solution here so I would like to know another options I have.

**Comment by FunkyloverOne** [comment]
Guys, are you sure you didn't forget to add this line to your Capfile?
`install_plugin Capistrano::Puma::Nginx`
For me it solved an issue, I'm using Capistrano 3.10.1

**Comment by kannans** [comment]
I'm using Capistrano 3.11.0. Have to include this plugin to Capfile.
`install_plugin Capistrano::Puma::Nginx`

**Comment by tom-lord** [comment]
@besi My answer above was a long time ago, and I unfortunately no longer have access to whatever project was being worked on at the time. It's possible that the code needs to be altered a little to accommodate modern library versions; [looking at this code](https://github.com/seuros/capistrano-puma/blob/e4ffe6d4f87c95cd08d777624728ee7f11eec8f3/lib/capistrano/tasks/nginx.rake#L1-L7) perhaps you now need to define `git_plugin = self` outside the namespace context?

I hope you're able to figure it out, and can potentially share a "working modern version" here for future Googlers 🤞

**Comment by besi** [comment]
@tom-lord Thanks very much for the heads up. I just tried to test it but for some strange reason my tasks which I define in `lib/capistrano/tasks` aren't properly loaded, despite the following line in my `Capfile`:

    # Loads custom tasks from `lib/capistrano/tasks' if you have any defined.
    Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }

I made a note in my code and if I finally manage to get it working I'll document it in this issue.

**Comment by besi** [comment]
If I `include Capistrano::PumaCommon` I have access to `puma_switch_user` but then the variable/property `backend` is not defined and the code fails.

I guess I would have to extend the module in order to mimic the behaviour of what the puma-plugin does. So I guess I have to let that be for now.

It would be easier for me to generate the configuration locally and then re-upload it to the folder of my choice.
